export enum EActionTypes {
  SIGNUP = 'SIGNUP',
  SET_ERROR = 'SET_ERROR',
  SIGNIN = 'SIGNIN',
  CLEAR_ERROR_MESSAGE = 'CLEAR_ERROR_MESSAGE',
  SIGNOUT = 'SIGNOUT',
  ADD_CURRENT_LOCATION = 'ADD_CURRENT_LOCATION',
}
